---
title: "Publications & Presentations"
---

## Technical publications

McCarty, S., Light, C., **Hei, Z.**, Panzik, J., Wolfe, P., & Fegley, M. (2026). *FRI Semester 3 Peer Mentor Mindsets Guide*. Binghamton University. [Open resource](https://shanemccarty.github.io/FRImindsets3/)

McCarty, S., Light, C., **Hei, Z.**, & Fegley, M. (2026). *FRI Peer Mentor Mindsets Guide*. Binghamton University. [Open resource](https://shanemccarty.github.io/FRImindsets/)

McCarty, S., & **Hei, Z**. (2025). Chapter contributions to *The Quantitative Playbook for Public Health Research in R*, S. McCarty (Ed.). [Open resource](https://shanemccarty.github.io/FRIplaybook/)

- McCarty, S., & **Hei, Z**. “Reproducible Reports.”
- **Hei, Z.**, & McCarty, S. “Import Data Once.”
- **Hei, Z.**, & McCarty, S. “Read Me.”
- **Hei, Z.** “Writing Methods & Results Reproducibly.”
- **Hei, Z.** “APA Citations & References.”
- **Hei, Z.** “Publish Your Report to Quarto Pub.”

## Conference abstracts

**Hei, Z.**, Giallella, J., & McCarty, S. (2026). *A Mixed-Methods Analysis of Promotion and Prevention Mindsets*. Poster abstract accepted by the American Public Health Association Annual Meeting. <https://apha.confex.com/apha/2026/meetingapp.cgi/Paper/594471>

## Presentations

McCarty, S., **Hei, Z.**, Rualo, G., Khalap, I., & Giallella, J. (2025, November). *Promotion & prevention mindsets: A four-study, mixed-methods approach*. Invited online presentation, Society for Community Research & Action.

**Hei, Z.**, et al. (2024, December). *Public Knowledge & Attitudes on Vaccinations and Reproductive Health*. FRI Proposal Poster Research Session, Binghamton University.

**Hei, Z.**, et al. (2023, December). *Endometriosis and Women’s Mental Health*. FRI Proposal Poster Research Session, Binghamton University.
